// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQF2pgnwI5qVfmewti0cyF5eQhAKT0nfk',
    appId: '1:116497196330:web:aa51cf43297cda285faa53',
    messagingSenderId: '116497196330',
    projectId: 'altpcs',
    authDomain: 'altpcs.firebaseapp.com',
    storageBucket: 'altpcs.appspot.com',
    measurementId: 'G-0TXCX58V6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3wifvZkfpkfQOWui8To0m0hA0LtaF3Yc',
    appId: '1:116497196330:android:83b4c2972afeeb595faa53',
    messagingSenderId: '116497196330',
    projectId: 'altpcs',
    storageBucket: 'altpcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOGrdwIz670JqUK5p0xHdk04uIDvFTe6Q',
    appId: '1:116497196330:ios:d1979a73f7c2749a5faa53',
    messagingSenderId: '116497196330',
    projectId: 'altpcs',
    storageBucket: 'altpcs.appspot.com',
    iosBundleId: 'com.example.alt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOGrdwIz670JqUK5p0xHdk04uIDvFTe6Q',
    appId: '1:116497196330:ios:57f880dd9e19a8ec5faa53',
    messagingSenderId: '116497196330',
    projectId: 'altpcs',
    storageBucket: 'altpcs.appspot.com',
    iosBundleId: 'com.example.alt.RunnerTests',
  );
}
